/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/X9ChF4G7Dyp
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function AfterBotti() {
  return (
    <Card className="max-w-md w-full mx-auto">
      <CardHeader className="flex flex-row items-center">
        <div className="flex items-center space-x-4">
          <Avatar>
            <AvatarImage alt="Image" src="/avatars/01.png" />
            <AvatarFallback>CB</AvatarFallback>
          </Avatar>
          <div>
            <p className="text-sm font-medium leading-none">Chatbotti</p>
            <p className="text-sm text-gray-500 dark:text-gray-400">Tervetuloa!</p>
          </div>
        </div>
      </CardHeader>
      <CardContent className="border-4 border-black bg-yellow-500 p-4">
        <div className="space-y-4">
          <div className="flex w-max max-w-[75%] flex-col gap-2 rounded-lg px-3 py-2 text-sm bg-blue-500 text-white dark:bg-blue-500 dark:text-white">
            Hei! Miten voin auttaa sinua tänään?
          </div>
          <div className="flex w-max max-w-[75%] flex-col gap-2 rounded-lg px-3 py-2 text-sm ml-auto bg-gray-900 text-gray-50 dark:bg-gray-50 dark:text-gray-900">
            Hei! Haluaisin tietää, millainen sää on tänään.
          </div>
          <div className="flex w-max max-w-[75%] flex-col gap-2 rounded-lg px-3 py-2 text-sm bg-blue-500 text-white dark:bg-blue-500 dark:text-white">
            Tänään on aurinkoinen ja lämmin päivä. Lämpötila on noin 20 astetta.
          </div>
          <div className="flex w-max max-w-[75%] flex-col gap-2 rounded-lg px-3 py-2 text-sm ml-auto bg-gray-900 text-gray-50 dark:bg-gray-50 dark:text-gray-900">
            Kuulostaa hyvältä! Entä mitä uutta on tapahtunut?
          </div>
          <div className="flex w-max max-w-[75%] flex-col gap-2 rounded-lg px-3 py-2 text-sm bg-blue-500 text-white dark:bg-blue-500 dark:text-white">
            Tänään uutisissa kerrottiin, että paikallinen urheiluseura voitti tärkeän ottelun. Muuten on ollut melko
            rauhallista.
          </div>
        </div>
      </CardContent>
      <CardFooter>
        <form className="flex w-full items-center space-x-2">
          <Input autoComplete="off" className="flex-1" id="message" placeholder="Kirjoita viestisi..." />
          <Button size="icon" type="submit">
            <SendIcon className="h-4 w-4" />
            <span className="sr-only">Lähetä</span>
          </Button>
        </form>
      </CardFooter>
    </Card>
  )
}

function SendIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>
  )
}
