/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/c727vrv9uMD
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function PetterinTaulukko() {
  return (
    <b a sortColumn sortDirection>
      {` b[sortColumn]) return sortDirection === 'asc' ? 1 : -1;
        return 0;
      });
    }, [flights, sortColumn, sortDirection]);
  
    return (
      `}
      <div className="w-full max-w-6xl mx-auto p-6">
        <h1 className="text-2xl font-bold mb-4">Flight Tracker</h1>
        <div className="overflow-x-auto">
          <table className="w-full table-auto border-collapse">
            <thead>
              <tr className="bg-gray-100 dark:bg-gray-800">
                <th className="px-4 py-3 text-left cursor-pointer">
                  Airline
                  <span className="ml-2">↑</span>
                </th>
                <th className="px-4 py-3 text-left cursor-pointer">
                  Flight
                  <span className="ml-2">↑</span>
                </th>
                <th className="px-4 py-3 text-left cursor-pointer">
                  Origin
                  <span className="ml-2">↑</span>
                </th>
                <th className="px-4 py-3 text-left cursor-pointer">
                  Destination
                  <span className="ml-2">↑</span>
                </th>
                <th className="px-4 py-3 text-left cursor-pointer">
                  Departure
                  <span className="ml-2">↑</span>
                </th>
                <th className="px-4 py-3 text-left cursor-pointer">
                  Arrival
                  <span className="ml-2">↑</span>
                </th>
                <th className="px-4 py-3 text-left cursor-pointer">
                  Status
                  <span className="ml-2">↑</span>
                </th>
                <th className="px-4 py-3 text-left cursor-pointer">
                  Weather
                  <span className="ml-2">↑</span>
                </th>
                <th className="px-4 py-3 text-left cursor-pointer">
                  Temp
                  <span className="ml-2">↑</span>
                </th>
              </tr>
            </thead>
            <tbody />
          </table>
        </div>
      </div>
    </b>
  )
}
